config/routes.rb
Rails.application.routes.draw do  

  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  get '/profile', to: 'users/profile#edit'
  patch '/profile', to: 'users/profile#update'
  delete '/profile', to: 'users/profile#destroy'

  get '/emergencyplan', to: 'staticpages#emergencyplan'
  post '/emergencyplan', to: 'staticpages#generate_pdf'

  get "/staticpages/download_pdf"
  
  get 'cron/notifications', to: 'cron#notifications'

  resources :information_bulletins
  resources :emergencies

  resources :sinisters do
    patch :approve
    patch :unapprove

    resources :alerts, only: [:show, :new, :create]
  end

  resources :news
end

app/models/information_bulletin.rb
class InformationBulletin < ActiveRecord::Base
  include ::SoftDeletable
  belongs_to :user
  validates :title, presence: { message: :title_required }
  validates :body, presence: { message: :description_required }

  has_attached_file :image, :styles => { :medium => "300x300>", :small => "150x150>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    where("lower(title) like ? or lower(body) like ?", "%#{query}%".downcase, "%#{query}%".downcase)
  end

end

app/controllers/information_bulletins_controller.rb
class InformationBulletinsController < ApplicationController
  before_action :require_admin, only: [:destroy,:edit,:update,:create]

  @@per_page = 9

  def index
    @information_bulletins = InformationBulletin.actives
    @information_bulletins = @information_bulletins.search params[:desc_or_title] if params[:desc_or_title]
    @information_bulletins =  @information_bulletins.paginate(:page => params[:page], :per_page => @@per_page)
  end

  def show
    @information_bulletin = InformationBulletin.find params[:id]
  end

  def new
    @information_bulletin = InformationBulletin.new
  end

  def create
    @information_bulletin = InformationBulletin.new
    @information_bulletin.user_id = current_user.id if current_user

    @information_bulletin.assign_attributes(post_params)

    if @information_bulletin.save
      redirect_to :information_bulletins, notice: I18n.t('information_bulletin.created_flash')
    else
      render :new
    end
  end

  def edit
    @information_bulletin = InformationBulletin.find params[:id]
  end

  def update
    @information_bulletin = InformationBulletin.find params[:id]
    if @information_bulletin.update_attributes post_params
      redirect_to :information_bulletins, notice: I18n.t('information_bulletin.created_flash')
    else
      render :action => :edit
    end
  end

  def destroy
    @information_bulletin = InformationBulletin.find params[:id]

    if @information_bulletin.soft_delete
      redirect_to :information_bulletins, notice: I18n.t('information_bulletin.deleted_flash')
    end
  end

  private

    def require_admin
      if !current_user || !current_user.is_admin?
        render :status => :forbidden, :text => t("actions.access_denied")
      end
    end

    def post_params
      permitted_parameters = [:title, :body,:image]
      params.require(:information_bulletin).permit(*permitted_parameters)
    end

end

app/helpers/information_bulletin_helper.rb
module InformationBulletinHelper
end

app/views/information_bulletins/_form.html.erb
<% content_for(:page_title, t('information_bulletin.new_information_bulletin')) %>

<% if @information_bulletin.persisted? %>
  <h1><%= t('information_bulletin.edit_information_bulletin') %></h1>
<% else %>
  <h1><%= t('information_bulletin.new_information_bulletin') %></h1>
<% end %>
  
<%= simple_form_for @information_bulletin do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :image %>
  <%= f.button :submit, t('information_bulletin.submit_add') %>
<% end %>

app/views/information_bulletins/edit.html.erb
<%= render :partial => 'form' %>

app/views/information_bulletins/index.html.erb
<% content_for(:page_title, t('information_bulletin.listing_header')) %>
<h1><%= t('information_bulletin.listing_header') %></h1>

<%= form_tag information_bulletins_path, method: "get" do %>
  <div>
    <%= text_field_tag :desc_or_title, nil, placeholder: t('information_bulletin.search.desc_or_title'),
        type: :search, value: params[:desc_or_title] %>
    <%= submit_tag t('information_bulletin.search.submit'), type: :submit, class: 'button', name: nil %>
  </div>
<% end %>

<ul class="tiles small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @information_bulletins.each do |elem| %>
    <li>
      <a href="<%= information_bulletin_path(elem) %>">
        <strong><%= elem.title %></strong>
        <% unless elem.image_file_name.nil? %>
          <%= image_tag elem.image.url(:thumb) %>
        <% end %>
        <p>
          <%= elem.body %>
        </p>
      </a>
    </li>
  <% end%>
</ul>

<div>
  <%= will_paginate @information_bulletins, :previous_label => '«', :next_label => '»', class: 'pagination' %>
</div>

<% if current_user && current_user.is_admin? %>
  <%= link_to t('information_bulletin.new_information_bulletin'), new_information_bulletin_path, class: 'button' %>
<% end %>

app/views/information_bulletins/new.html.erb
<%= render :partial => 'form' %>

app/views/information_bulletins/show.html.erb
<h1><%= @information_bulletin.title%></h1>

<% unless @information_bulletin.image_file_name.nil? %>
  <%= image_tag @information_bulletin.image.url(:medium), class: 'right-large-up' %>
<% end %>

<p>
  <%= @information_bulletin.body %>
</p>

<div>
  <%= link_to t('back'), information_bulletins_path, class: 'button' %>
  <%if current_user && current_user.is_admin? %>
      <%= link_to t('actions.modify'),
        edit_information_bulletin_path(@information_bulletin), class: 'button'  %>
      <%= link_to t('actions.delete'), information_bulletin_path(@information_bulletin),
        method: :delete,
        data: { confirm: t('actions.delete_confirm', title: @information_bulletin.title) }, class: 'button alert' %>
  <%end%>
</div>