config/routes.rb
Rails.application.routes.draw do  

  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  get '/profile', to: 'users/profile#edit'
  patch '/profile', to: 'users/profile#update'
  delete '/profile', to: 'users/profile#destroy'

  get '/emergencyplan', to: 'staticpages#emergencyplan'
  post '/emergencyplan', to: 'staticpages#generate_pdf'

  get "/staticpages/download_pdf"
  
  get 'cron/notifications', to: 'cron#notifications'

  resources :information_bulletins
  resources :emergencies

  resources :sinisters do
    patch :approve
    patch :unapprove

    resources :alerts, only: [:show, :new, :create]
  end

  resources :news
end

app/models/emergency.rb
class Emergency < ActiveRecord::Base
end

app/controllers/emergencies_controller.rb
class EmergenciesController < ApplicationController
  before_action :require_admin, except: :index

  def index
    @emergencies = Emergency.all
  end

  def new
    @emergencies = Emergency.new
  end

  def create
    @emergencies = Emergency.new

    @emergencies.assign_attributes(post_params)

    if @emergencies.save
      redirect_to :emergencies, notice: I18n.t('emergencies.created_flash')
    else
      render :new
    end
  end

  def edit
    @emergencies = Emergency.find params[:id]
  end

  def update
    @emergencies = Emergency.find params[:id]
    if @emergencies.update_attributes post_params
      redirect_to :emergencies, notice: I18n.t('emergencies.created_flash')
    else
      render :action => :edit
    end
  end

  def destroy
    @emergencies = Emergency.find params[:id]

    if @emergencies.destroy
      redirect_to :back, notice: I18n.t('emergencies.deleted_flash')
    end
  end

  private

    def require_admin
      if !current_user || !current_user.is_admin?
        render :status => :forbidden, :text => t("actions.access_denied")
      end
    end

    def post_params
      permitted_parameters = [:organization, :phone,:web_site]
      params.require(:emergency).permit(*permitted_parameters)
    end

end

app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

app/views/emergencies/_form.html.erb
<% content_for(:page_title, t('emergencies.new')) %>

<% if @emergencies.persisted? %>
  <h1><%= t('emergencies.edit') %></h1>
<% else %>
  <h1><%= t('emergencies.new') %></h1>
<% end %>
  
<%= simple_form_for @emergencies do |f| %>
  <%= f.input :organization %>
  <%= f.input :phone %>
  <%= f.input :web_site,:placeholder => "inclure le protocole complet http://" %>
  <%= f.button :submit, t('information_bulletin.submit_add') %>
<% end %>

app/views/emergencies/edit.html.erb
<%= render :partial => 'form' %>

app/views/emergencies/index.html.erb
<% content_for(:page_title, t('emergencies.listing_header')) %>
<h1><%= t('emergencies.listing_header') %></h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= t('activerecord.attributes.emergency.organization') %></th>
      <th scope="col"><%= t('activerecord.attributes.emergency.phone') %></th>
      <th scope="col"><%= t('activerecord.attributes.emergency.web_site') %></th>
      <%if current_user && current_user.is_admin? %>
        <th scope="col"><%= t('actions.title') %></th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @emergencies.each do |emergency| %>
      <tr>
        <td><%= emergency.organization %></td>
        <td><%= emergency.phone %></td>
        <td><%= link_to emergency.web_site, emergency.web_site, :target => "_blank" %></td>
        <%if current_user && current_user.is_admin? %>
          <td>
            <%= link_to t('actions.modify'),
              edit_emergency_path(emergency) %>
            <%= link_to t('actions.delete'), emergency_path(emergency),
              method: :delete,
              data: { confirm: t('actions.delete_confirm', title: emergency.organization) } %>
          </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<% if (current_user && current_user.is_admin?) %>
  <%= link_to new_emergency_path(back_page: params[:page]), :class => "button" do %>
    <%= t('emergencies.new') %>
  <% end %>
<% end %>

app/views/emergencies/new.html.erb
<%= render :partial => 'form' %>