config/routes.rb
Rails.application.routes.draw do  

  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  get '/profile', to: 'users/profile#edit'
  patch '/profile', to: 'users/profile#update'
  delete '/profile', to: 'users/profile#destroy'

  get '/emergencyplan', to: 'staticpages#emergencyplan'
  post '/emergencyplan', to: 'staticpages#generate_pdf'

  get "/staticpages/download_pdf"
  
  get 'cron/notifications', to: 'cron#notifications'

  resources :information_bulletins
  resources :emergencies

  resources :sinisters do
    patch :approve
    patch :unapprove

    resources :alerts, only: [:show, :new, :create]
  end

  resources :news
end

app/models/sinister.rb
class Sinister < ActiveRecord::Base
  include ::SoftDeletable, ::Approvable
  has_many :alerts
  belongs_to :user
  belongs_to :category
  validates :title, presence: { message: :title_required }
  validates :description, presence: { message: :description_required }
  validates :sinister_date, presence: true
  validates :longitude, presence: { message: :longitude_required }
  validates :latitude, presence: { message: :latitude_required }
  validates :category_id, presence: { message: :category_required }

  has_attached_file :image, :styles => { :medium => "300x300>", :small => "150x150>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    where("lower(title) like ? or lower(description) like ?", "%#{query}%".downcase, "%#{query}%".downcase)
  end
end

app/controllers/sinisters_controller.rb
class SinistersController < ApplicationController
  before_action :require_admin, only: [:destroy,:edit,:update]

  @@per_page = 9

  def index
    @sinisters = Sinister.actives.order('sinister_date DESC')
    @sinisters = @sinisters.search params[:desc_or_title] if params[:desc_or_title]
    @sinisters = @sinisters.approved unless current_user && current_user.is_admin?
    @sinisters = @sinisters.paginate(:page => params[:page], :per_page => @@per_page)
  end

  def show
    @sinister = Sinister.find params[:id]
  end

  def new
    @sinister = Sinister.new
  end

  def create
    @sinister = Sinister.new
    @sinister.user_id = current_user.id if current_user

    @sinister.assign_attributes(post_params)

    if @sinister.save
      redirect_to :sinisters, notice: I18n.t('sinister.created_flash')
    else
      render :new
    end
  end

  def edit
    @sinister = Sinister.find params[:id]
  end

  def update
    @sinister = Sinister.find params[:id]
    if @sinister.update_attributes post_params
      redirect_to :sinisters, notice: I18n.t('sinister.created_flash')
    else
      render :action => :edit
    end
  end

  def destroy
    @sinister = Sinister.find params[:id]

    if @sinister.soft_delete
      redirect_to sinisters_path, notice: I18n.t('sinister.deleted_flash')
    end
  end

  def approve
    @sinister = Sinister.find params[:sinister_id]

    if @sinister.approve
      redirect_to :back, notice: I18n.t('sinister.approved_flash')
    end
  end

  def unapprove
    @sinister = Sinister.find params[:sinister_id]

    if @sinister.unapprove
      redirect_to :back, notice: I18n.t('sinister.unapproved_flash')
    end
  end

  private
    def post_params
      permitted_parameters = [:title, :description, :sinister_date, :longitude, :latitude, :category_id, :image]
      params.require(:sinister).permit(*permitted_parameters)
    end

end

app/helpers/sinister_helper.rb
module SinisterHelper
end

app/views/sinisters/_form.html.erb
<% content_for(:page_title, t('sinister.new_sinister')) %>

<% if @sinister.persisted? %>
  <h1><%= t('sinister.edit_sinister') %></h1>
<% else %>
  <h1><%= t('sinister.new_sinister') %></h1>
<% end %>
  
<%= simple_form_for @sinister do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :category_id, label: t('sinister.form.category_label'), collection: Category.all,
              prompt: t('sinister.form.select_category_prompt') %>
  <%= f.input :sinister_date, as: :datetime, value: Date.today %>
  <%= f.input :image %>
  <% if @sinister.longitude %>
    <%= f.input :longitude %>
    <%= f.input :latitude %>
  <% else %>
    <div class="geolocation-component"></div>
  <% end %>
  <%= f.button :submit, t('actions.submit_add') %>
<% end %>

app/views/sinisters/edit.html.erb
<%= render :partial => 'form' %>

app/views/sinisters/index.html.erb
<% content_for(:page_title, t('sinister.listing_header')) %>
<h1><%= t('sinister.listing_header') %></h1>

<%= form_tag sinisters_path, method: "get" do %>
  <div>
    <%= text_field_tag :desc_or_title, nil, placeholder: t('sinister.search.desc_or_title'),
        type: :search, value: params[:desc_or_title] %>
    <%= submit_tag t('sinister.search.submit'), type: :submit, class: 'button', name: nil %>
  </div>
<% end %>

<ul class="tiles small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @sinisters.each do |sinister| %>
    <li>
      <a href="<%= sinister_path(sinister) %>">
        <strong><%= sinister.title %></strong>
        <% unless sinister.image_file_name.nil? %>
          <%= image_tag sinister.image.url(:thumb) %>
        <% end %>
        <time datetime="<%= sinister.sinister_date.utc.iso8601 %>"><%= l sinister.sinister_date, format: :short%></time>
        <p>
          <%= sinister.description %>
        </p>
      </a>
    </li>
  <% end%>
</ul>

<div>
  <%= will_paginate @sinisters, :previous_label => '«', :next_label => '»', class: 'pagination' %>
</div>

<%= link_to t('sinister.new_sinister'), new_sinister_path, class: 'button' %>

app/views/sinisters/new.html.erb
<%= render :partial => 'form' %>

<div id="gmap"></div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>

app/views/sinisters/show.html.erb
<h1><%= @sinister.title%></h1>

<% unless @sinister.image_file_name.nil? %>
    <%= image_tag @sinister.image.url(:medium), class: 'right-large-up' %>
<% end %>

<dl>
  <dt><%= t('activerecord.attributes.sinister.sinister_date')%></dt>
  <dd><time datetime="<%= @sinister.sinister_date.utc.iso8601 %>"><%= l @sinister.sinister_date, format: :long %></time></dd>
  <dt><%= t('activerecord.attributes.sinister.user_name')%></dt>
  <dd>
    <%= @sinister.user.name if @sinister.user_id %>
    <%= t('activerecord.attributes.sinister.user_anonymous') if !@sinister.user_id %>
  </dd>
</dl>

<p>
  <%= @sinister.description %>
</p>

<p>
  <a target="_blank" href="<%= "http://maps.google.com/maps?z=12&t=m&q=loc:#{@sinister.longitude}+#{@sinister.latitude}" %>" >Voir sur la carte</a>
</p>


<table class="table">
  <h2>
    Alertes diffusées pour ce sinistre
  </h2>
  <thead>
    <tr>
      <th scope="col"><%= t('activerecord.attributes.alert.title') %></th>
      <th scope="col"><%= t('activerecord.attributes.alert.message') %></th>
      <th scope="col"><%= t('activerecord.attributes.alert.publication_date') %></th> 
      <% if current_user && current_user.is_admin? %>
        <th scope="col"><%= t('alert.is_published') %></th> 
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @sinister.alerts.each do |alert| %>
      <tr>
        <td><%= alert.title %></td>
        <td><%= alert.message %></td>
        <td><time datetime="<%= alert.publication_date.utc.iso8601 %>"><%= l alert.publication_date, format: :short %></time></td>
        <% if current_user && current_user.is_admin? %>
          <td><%= alert.published_at.nil? ? t('table_no') : t('table_yes') %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to t('back'), sinisters_path, class: 'button' %>
  <%if current_user && current_user.is_admin? %>
      <%= link_to t('actions.modify'),
        edit_sinister_path(@sinister), class: 'button'  %>
      <%= link_to t('actions.approve'), sinister_approve_path(@sinister), class: 'button', method: :patch unless @sinister.approved? %>
      <%= link_to t('actions.unapprove'), sinister_unapprove_path(@sinister), method: :patch, class: 'button'if @sinister.approved? %>
      <%= link_to 'Créer une alerte', new_sinister_alert_path(@sinister), class: 'button' %>
      <%= link_to t('actions.delete'), sinister_path(@sinister),
        method: :delete,
        data: { confirm: t('actions.delete_confirm', title: @sinister.title) }, class: 'button alert' %>
  <%end%>
</div>