config/routes.rb
Rails.application.routes.draw do  

  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  get '/profile', to: 'users/profile#edit'
  patch '/profile', to: 'users/profile#update'
  delete '/profile', to: 'users/profile#destroy'

  get '/emergencyplan', to: 'staticpages#emergencyplan'
  post '/emergencyplan', to: 'staticpages#generate_pdf'

  get "/staticpages/download_pdf"
  
  get 'cron/notifications', to: 'cron#notifications'

  resources :information_bulletins
  resources :emergencies

  resources :sinisters do
    patch :approve
    patch :unapprove

    resources :alerts, only: [:show, :new, :create]
  end

  resources :news
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% is_admin = current_user && current_user.is_admin? %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Faire Face - Ville De Québec</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "vendor/modernizr" %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to root_path, class: :"navbar-brand" do %>
              <span>
                <span class="faire">Faire</span><span class="face">Face</span>
              </span>
            <% end %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <% if current_user %>
            <li><%= link_to('Profil', profile_path) %></li>
            <li><%= link_to(current_user.email + '(Déconnexion)', destroy_user_session_path, method: :delete) %></li>
          <% else %>
            <li><a href="<%= new_user_session_path %>">Connexion</a></li>
            <li><a href="<%= new_user_registration_path %>">Inscription</a></li>
          <% end %>
        </ul>

        <ul class="left">
          <li class="has-dropdown">
            <a href="#"><%= t('sinister.listing_header') %></a>
            <% if is_admin && nb_sinisters_notifications != 0 %>
              <span style="display: none;" class="badge"><%= nb_sinisters_notifications %></span>
            <% end %>
            <ul class="dropdown">
              <li><%= link_to t('sinister.listing_header'), sinisters_path %></li>
              <li><%= link_to t('sinister.new_sinister'), new_sinister_path %></li>
            </ul>
          </li>
          <li <% if is_admin %>class="has-dropdown"<% end %>>
            <%= link_to t('new.listing_header'), news_index_path %>
            <% if is_admin %>
              <ul class="dropdown">
                <li><%= link_to t('new.listing_header'), news_index_path %></li>
                <li><%= link_to t('new.new_new'), new_news_path %></li>
              </ul>
            <% end %>
          </li>
          <li <% if is_admin %>class="has-dropdown"<% end %>>
            <%= link_to t('information_bulletin.listing_header'), information_bulletins_path %>
            <% if is_admin %>
              <ul class="dropdown">
                <li><%= link_to t('information_bulletin.listing_header'), information_bulletins_path %></li>
                <li><%= link_to t('information_bulletin.new_information_bulletin'), new_information_bulletin_path %></li>
              </ul>
            <% end %>
          </li>
          <li><%= link_to t('emergencies.listing_header'), emergencies_path %></li>
          <li><%= link_to t('emergencyplan.listing_header'), emergencyplan_path %></li>
        </ul>
      </section>
    </nav>
    <% flash.each do |name, msg| %>
      <% if msg.is_a? String %>
        <div data-alert class="alert-box <%= name %>">
            <%= msg %>
        </div>
      <% end %>
    <% end %>
    <main >
      <div class="row">
        <div class="small-12">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer>
        <a href="<%= asset_path('guide.pdf') %>">
            Guide utilisateur
        </a>
    </footer>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>